/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Clientes.ListaCliente;
import Envios.Envio;
import Envios.GestionEnvios;
import Paquetes.ListaPaquete;
import Paquetes.Paquete;
import RutasEntrega.ListaRutasEntrega;
import RutasEntrega.RutaEntrega;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class FrmEnvios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEmpleados
     */
    private ListaPaquete listP;
    private ListaCliente listC;
    private GestionEnvios listE;
    private ListaRutasEntrega listR;
    public FrmEnvios() {
        initComponents();
        DisableorActiveAll(false);
        listP = ListaPaquete.getInstance();
        listE = GestionEnvios.getInstance();
        listC = ListaCliente.getInstance();
       listR= ListaRutasEntrega.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddLbl = new javax.swing.JLabel();
        buscarLbl = new javax.swing.JLabel();
        DeleteLbl = new javax.swing.JLabel();
        ActualizarLbl = new javax.swing.JLabel();
        ListoLbl = new javax.swing.JButton();
        CancelLbl = new javax.swing.JButton();
        ActualizarLbl1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        SalarioLbl = new javax.swing.JLabel();
        CedulaLbl = new javax.swing.JLabel();
        NumeroEnvioTxt = new javax.swing.JTextField();
        NombreLbl = new javax.swing.JLabel();
        FechaNLbl = new javax.swing.JLabel();
        CorreoLbl = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        CedulaTxt = new javax.swing.JFormattedTextField();
        jComboBoxPaquete = new javax.swing.JComboBox<>();
        SalarioLbl3 = new javax.swing.JLabel();
        jComboBoxRuta = new javax.swing.JComboBox<>();
        SalarioLbl4 = new javax.swing.JLabel();
        PrecioTxt = new javax.swing.JTextField();
        FechaNLbl1 = new javax.swing.JLabel();
        FechaETxt1 = new javax.swing.JFormattedTextField();
        FechaETxt = new javax.swing.JFormattedTextField();
        EstadoLbl = new javax.swing.JLabel();
        EstadoTxt = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setPreferredSize(new java.awt.Dimension(840, 421));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 206, 84));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-trabajo-permanente-24.png"))); // NOI18N
        jLabel1.setText("                                                            Administrar Envios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(46, 62, 78));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Opciones");

        AddLbl.setBackground(new java.awt.Color(255, 255, 255));
        AddLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-añadir-usuario-masculino-24.png"))); // NOI18N
        AddLbl.setText("Registrar Envio");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        buscarLbl.setBackground(new java.awt.Color(255, 255, 255));
        buscarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buscarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-encuentra-hombre-usuario-24.png"))); // NOI18N
        buscarLbl.setText("Buscar");
        buscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarLblMouseClicked(evt);
            }
        });

        DeleteLbl.setBackground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        DeleteLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-eliminar-usuario-masculino-24.png"))); // NOI18N
        DeleteLbl.setText("Despachar");
        DeleteLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteLblMouseClicked(evt);
            }
        });

        ActualizarLbl.setBackground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ActualizarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-editar-usuaria-24.png"))); // NOI18N
        ActualizarLbl.setText("Entregar");
        ActualizarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLblMouseClicked(evt);
            }
        });

        ListoLbl.setBackground(new java.awt.Color(46, 62, 78));
        ListoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        ListoLbl.setBorderPainted(false);
        ListoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListoLblMouseClicked(evt);
            }
        });
        ListoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoLblActionPerformed(evt);
            }
        });

        CancelLbl.setBackground(new java.awt.Color(46, 62, 78));
        CancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-delete-24.png"))); // NOI18N
        CancelLbl.setBorderPainted(false);
        CancelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelLblMouseClicked(evt);
            }
        });
        CancelLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLblActionPerformed(evt);
            }
        });

        ActualizarLbl1.setBackground(new java.awt.Color(255, 255, 255));
        ActualizarLbl1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ActualizarLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-editar-usuaria-24.png"))); // NOI18N
        ActualizarLbl1.setText("Cancelar");
        ActualizarLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActualizarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ActualizarLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(DeleteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActualizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActualizarLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        SalarioLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SalarioLbl.setForeground(new java.awt.Color(255, 255, 255));
        SalarioLbl.setText("Paquete:");

        CedulaLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaLbl.setForeground(new java.awt.Color(255, 255, 255));
        CedulaLbl.setText("Numero de Envio:");

        NumeroEnvioTxt.setEditable(false);
        NumeroEnvioTxt.setBackground(new java.awt.Color(204, 204, 204));
        NumeroEnvioTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NumeroEnvioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroEnvioTxtActionPerformed(evt);
            }
        });

        NombreLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(255, 255, 255));
        NombreLbl.setText("Cedula Cliente:");

        FechaNLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaNLbl.setForeground(new java.awt.Color(255, 255, 255));
        FechaNLbl.setText("Fecha Entrega:");

        CorreoLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CorreoLbl.setForeground(new java.awt.Color(255, 255, 255));
        CorreoLbl.setText("Nombre Cliente:");

        NombreTxt.setEditable(false);
        NombreTxt.setBackground(new java.awt.Color(204, 204, 204));
        NombreTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        CedulaTxt.setBackground(new java.awt.Color(204, 204, 204));
        CedulaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        jComboBoxPaquete.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPaqueteItemStateChanged(evt);
            }
        });

        SalarioLbl3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SalarioLbl3.setForeground(new java.awt.Color(255, 255, 255));
        SalarioLbl3.setText("Ruta:");

        jComboBoxRuta.setBackground(new java.awt.Color(204, 204, 204));

        SalarioLbl4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SalarioLbl4.setForeground(new java.awt.Color(255, 0, 51));
        SalarioLbl4.setText("Precio:");

        PrecioTxt.setEditable(false);
        PrecioTxt.setBackground(new java.awt.Color(204, 204, 204));
        PrecioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTxtActionPerformed(evt);
            }
        });

        FechaNLbl1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaNLbl1.setForeground(new java.awt.Color(255, 255, 255));
        FechaNLbl1.setText("Fecha Envio:");

        FechaETxt1.setEditable(false);
        FechaETxt1.setBackground(new java.awt.Color(204, 204, 204));
        FechaETxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MM yyyy"))));
        FechaETxt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FechaETxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaETxt1ActionPerformed(evt);
            }
        });

        FechaETxt.setBackground(new java.awt.Color(204, 204, 204));
        FechaETxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FechaETxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FechaETxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaETxtActionPerformed(evt);
            }
        });

        EstadoLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EstadoLbl.setForeground(new java.awt.Color(255, 255, 255));
        EstadoLbl.setText("Estado:");

        EstadoTxt.setEditable(false);
        EstadoTxt.setBackground(new java.awt.Color(204, 204, 204));
        EstadoTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EstadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(NumeroEnvioTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CedulaLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FechaNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(NombreTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CorreoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))))
                                    .addComponent(FechaETxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SalarioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EstadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SalarioLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FechaNLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SalarioLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(PrecioTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(FechaETxt1, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EstadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CedulaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalarioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroEnvioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalarioLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CorreoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FechaNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(FechaNLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FechaETxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalarioLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaETxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroEnvioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroEnvioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroEnvioTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
          this.ClearTxt();
        JTextField textField = new JTextField();
        Object[] message = {
            "Ingrese la cédula del cliente al que le pertenece el tramite:", textField
        };
        int option = JOptionPane.showConfirmDialog(null, message, "Entrada de Cédula", JOptionPane.OK_CANCEL_OPTION);
        String id = textField.getText();
        if((option == JOptionPane.OK_OPTION&&!textField.getText().isEmpty()&&this.listC.SearchCliente(id)!=null)){
        DisableorActiveAll(true);
        this.jComboBoxPaquete.removeAllItems();
        actualizarComboBoxP(this.listC.SearchCliente(id).getPaquetes().getPaquetesL());
        this.NumeroEnvioTxt.setText(String.valueOf(this.listE.getListaEnvios().size()+1));
        this.CedulaTxt.setText(id);
        this.NombreTxt.setText(this.listC.SearchCliente(id).getNombre());
        this.FechaETxt1.setText(String.valueOf(LocalDate.now()));
          actualizarComboBoxR(this.listR.getRutas());
          this.EstadoLbl.setVisible(false);
          this.EstadoTxt.setVisible(false);
        }else{
         JOptionPane.showMessageDialog(null, "Cédula no existente, intente de nuevo", "Alerta", JOptionPane.WARNING_MESSAGE);    
        }
    }//GEN-LAST:event_AddLblMouseClicked
 public void actualizarComboBoxR(HashSet<RutaEntrega> e) {
     
        for ( RutaEntrega es : e) {
            this.jComboBoxRuta.addItem(es.getCodigo());
        }
        
    }
  public void actualizarComboBoxP(HashMap<String,Paquete> e) {
     
        for ( Map.Entry<String, Paquete> entry : e.entrySet()) {
            this.jComboBoxPaquete.addItem(entry.getValue().getCodigo());
        }
        
    }
    private void buscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLblMouseClicked
        // TODO add your handling code here:
          DisableorActiveAll(false);
        this.CedulaLbl.setEnabled(true);
         this.CedulaLbl.setVisible(true);
          this.CedulaLbl.setText("Numero de Envio a Buscar");
           this.NumeroEnvioTxt.setEditable(true);
        this.NumeroEnvioTxt.setEnabled(true);
        this.NumeroEnvioTxt.setVisible(true);
    }//GEN-LAST:event_buscarLblMouseClicked

    private void DeleteLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteLblMouseClicked
        // TODO add your handling code here:
      DisableorActiveAll(false);
        this.CedulaLbl.setEnabled(true);
         this.CedulaLbl.setVisible(true);
          this.CedulaLbl.setText("Presione listo para despachar!");
           this.NumeroEnvioTxt.setEditable(true);

    }//GEN-LAST:event_DeleteLblMouseClicked

    private void ActualizarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLblMouseClicked
        // TODO add your handling code here:
      DisableorActiveAll(false);
        this.CedulaLbl.setEnabled(true);
         this.CedulaLbl.setVisible(true);
          this.CedulaLbl.setText("Numero de Envio a Entregar");
           this.NumeroEnvioTxt.setEditable(true);
        this.NumeroEnvioTxt.setEnabled(true);
        this.NumeroEnvioTxt.setVisible(true);
    }//GEN-LAST:event_ActualizarLblMouseClicked

    private void ActualizarLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLbl1MouseClicked
          DisableorActiveAll(false);
        this.CedulaLbl.setEnabled(true);
         this.CedulaLbl.setVisible(true);
          this.CedulaLbl.setText("Numero de Envio a Cancelar");
           this.NumeroEnvioTxt.setEditable(true);
        this.NumeroEnvioTxt.setEnabled(true);
        this.NumeroEnvioTxt.setVisible(true);
    }//GEN-LAST:event_ActualizarLbl1MouseClicked

    private void PrecioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTxtActionPerformed

    private void CancelLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelLblMouseClicked
this.ClearTxt();
this.DisableorActiveAll(false);

    }//GEN-LAST:event_CancelLblMouseClicked

    private void ListoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListoLblMouseClicked
   
    }//GEN-LAST:event_ListoLblMouseClicked

    private void FechaETxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaETxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaETxt1ActionPerformed

    private void jComboBoxPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPaqueteItemStateChanged
        // TODO add your handling code here:
        if(this.jComboBoxPaquete.getSelectedItem()!=null){
       String id = this.jComboBoxPaquete.getSelectedItem().toString();
      Paquete p = this.listP.buscarPaquete(id);
      this.PrecioTxt.setText("₡"+String.valueOf(this.calcularPrecio1(Double.parseDouble(p.getPeso().trim().replace(",", ".")))));
        }
    }//GEN-LAST:event_jComboBoxPaqueteItemStateChanged

    private void ListoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoLblActionPerformed
        // TODO add your handling code here:
        if(NombreLbl.isVisible()){
          try {
              if( isFechaAntesDeHoy(this.FechaETxt.getText())){
                  JOptionPane.showMessageDialog(null, "La fecha de entrega no puede ser anterior a la fecha actual", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
              }else if(listC.SearchCliente(CedulaTxt.getText())==null){
                  JOptionPane.showMessageDialog(null, "El cliente no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
              }else{
                  Envio envio  = new Envio(listC.SearchCliente(CedulaTxt.getText()),
                          listP.buscarPaquete(jComboBoxPaquete.getSelectedItem().toString()),
                          listR.buscarRuta(jComboBoxRuta.getSelectedItem().toString()),convertirStringAFecha(this.FechaETxt.getText()));
                  System.out.println("entro a fecha envio "+this.FechaETxt.getText());
                  System.out.println(envio.getRuta().getDescripcion());
                  listE.registrarEnvio(envio);
                 
             
                  JOptionPane.showMessageDialog(null, "Envio Registrado, Codigo : "+envio.getNumeroEnvio(), "A nombre del cliente: "+listC.SearchCliente(CedulaTxt.getText()).getNombre(), JOptionPane.WARNING_MESSAGE);
                       this.ClearTxt();
                  this.DisableorActiveAll(false); 
              }
          } catch (ParseException ex) {
              Logger.getLogger(FrmEnvios.class.getName()).log(Level.SEVERE, null, ex);
          }
  }else if(CedulaLbl.getText().equals("Numero de Envio a Buscar")){
       if(listE.buscarEnvio(Integer.parseInt(this.NumeroEnvioTxt.getText()))!=null){
     
            Envio envio = listE.buscarEnvio(Integer.parseInt(this.NumeroEnvioTxt.getText()));
            this.NumeroEnvioTxt.setText(String.valueOf(envio.getNumeroEnvio()));
            this.CedulaTxt.setText(envio.getCliente().getCedula());
            this.NombreTxt.setText(envio.getCliente().getNombre());
            FechaETxt.setText(String.valueOf(envio.getFechaEntrega()));
            FechaETxt1.setText(String.valueOf(envio.getFechaEntrega()));
            jComboBoxPaquete.addItem(envio.getPaquete().getCodigo());
            jComboBoxRuta.addItem(envio.getRuta().getCodigo());
            this.EstadoTxt.setText(envio.getEstado());
            DisableorActiveAll(true);
            }else{
                JOptionPane.showMessageDialog(null, "El envio no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
            }
  }else if(CedulaLbl.getText().equals("Presione listo para despachar!")){
                    if(this.listE.getCantidadEnviosNoNulosQ()>0){
                   listE.despacharEnvio();
              ClearTxt();
               JOptionPane.showMessageDialog(null, "Envio Despachado!", "completado", JOptionPane.WARNING_MESSAGE);
                    }else{
                       JOptionPane.showMessageDialog(null, "El envio no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                    }
  }else if (CedulaLbl.getText().equals("Numero de Envio a Entregar")){
      if(listE.buscarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()))!=null){
            if(this.listE.getCantidadEnviosNoNulosQ()>0){
       listE.entregarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()));
       ClearTxt();
        JOptionPane.showMessageDialog(null, "Envio Entregado!", "completado", JOptionPane.WARNING_MESSAGE);
            }else{
            JOptionPane.showMessageDialog(null, "El envio no existe en la cola de envios", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
            }
  }else{
       JOptionPane.showMessageDialog(null, "El envio no existe en la cola de envios", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
  }
  }else if(CedulaLbl.getText().equals("Numero de Envio a Cancelar")){
      
          if(listE.buscarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()))!=null){
              if(this.listE.getCantidadEnviosNoNulosQ()>0){
       listE.cancelarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()));
       ClearTxt();
        JOptionPane.showMessageDialog(null, "Envio Cancelado!", "completado", JOptionPane.WARNING_MESSAGE);
              }else{
                        JOptionPane.showMessageDialog(null, "El envio no existe en la cola de envios", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
              }
  }else{
       JOptionPane.showMessageDialog(null, "El envio no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
  } 
  }
    }//GEN-LAST:event_ListoLblActionPerformed

    private void FechaETxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaETxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaETxtActionPerformed

    private void EstadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoTxtActionPerformed

    private void CancelLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLblActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CancelLblActionPerformed

public void DisableorActiveAll(boolean bool){
    this.CedulaLbl.setEnabled(bool);
    this.CedulaLbl.setVisible(bool);
    this.NumeroEnvioTxt.setEnabled(bool);
    this.NumeroEnvioTxt.setVisible(bool);
    this.NombreLbl.setEnabled(bool);
    this.NombreLbl.setVisible(bool);
    this.CedulaTxt.setEnabled(bool);
    this.CedulaTxt.setVisible(bool);
    this.FechaNLbl.setEnabled(bool);
    this.FechaNLbl.setVisible(bool);
    this.FechaETxt.setEnabled(bool);
    this.FechaETxt.setVisible(bool);
     this.CorreoLbl.setEnabled(bool);
    this.CorreoLbl.setVisible(bool);
    this.NombreTxt.setEnabled(bool);
    this.NombreTxt.setVisible(bool);
    this.SalarioLbl.setEnabled(bool);
    this.SalarioLbl.setVisible(bool);
    this.jComboBoxPaquete.setEnabled(bool);
    this.jComboBoxPaquete.setVisible(bool);
    this.SalarioLbl3.setEnabled(bool);
    this.SalarioLbl3.setVisible(bool);
    this.jComboBoxRuta.setEnabled(bool);
    this.jComboBoxRuta.setVisible(bool);
    this.SalarioLbl.setEnabled(bool);
    this.SalarioLbl.setVisible(bool);
    this.SalarioLbl4.setEnabled(bool);
    this.SalarioLbl4.setVisible(bool);
     this.PrecioTxt.setEnabled(bool);
    this.PrecioTxt.setVisible(bool);
    this.FechaNLbl1.setEnabled(bool);
    this.FechaNLbl1.setVisible(bool);
     this.FechaETxt1.setEnabled(bool);
    this.FechaETxt1.setVisible(bool);
    this.EstadoLbl.setVisible(bool);
      this.EstadoLbl.setEnabled(bool);
       this.EstadoTxt.setVisible(bool);
      this.EstadoTxt.setEnabled(bool);
}

public void ClearTxt(){
    this.NumeroEnvioTxt.setText("");
    this.CedulaTxt.setText("");
    this.NombreTxt.setText("");
    this.FechaETxt.setText("");
    this.PrecioTxt.setText("");
    this.EstadoTxt.setText("");
    this.jComboBoxPaquete.removeAllItems();
    this.jComboBoxRuta.removeAllItems();
       
}
 public LocalDate convertirStringAFecha(String fechaStr) {
        try {
            if (fechaStr == null || fechaStr.isEmpty()) {
                throw new IllegalArgumentException("La fecha no puede estar vacía.");
            }
            
            // Especifica el formato de la fecha si es necesario
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
            
            // Intenta parsear el String a LocalDate
            return LocalDate.parse(fechaStr, formatter);
        } catch (DateTimeParseException e) {
            System.out.println("Error al parsear la fecha: " + e.getMessage());
            return null; // O manejar el error según sea necesario
        }
    }
  private double calcularPrecio1(double peso) {
        return 2100 + (peso > 1 ? (peso - 1) * 1200 : 0);
    }
  
   public static boolean isFechaAntesDeHoy(String fechaTexto) throws ParseException {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            // Verifica si el campo de texto no está vacío
            if (fechaTexto == null || fechaTexto.trim().isEmpty()) {
                throw new IllegalArgumentException("El campo de fecha está vacío.");
            }

            // Convierte el texto de la fecha a un objeto Date
            Date fechaIngresada = formatter.parse(fechaTexto);

            // Obtiene la fecha actual
            Date fechaActual = new Date();

            // Comprueba si la fecha ingresada es anterior a la fecha actual
            return fechaIngresada.before(fechaActual);

        }catch (IllegalArgumentException e) {
            // Maneja el caso de campo de texto vacío u otro error
            System.out.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "El campo de fecha no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        // Captura y maneja el error de parseo de la fecha
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarLbl;
    private javax.swing.JLabel ActualizarLbl1;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JButton CancelLbl;
    private javax.swing.JLabel CedulaLbl;
    private javax.swing.JFormattedTextField CedulaTxt;
    private javax.swing.JLabel CorreoLbl;
    private javax.swing.JLabel DeleteLbl;
    private javax.swing.JLabel EstadoLbl;
    private javax.swing.JTextField EstadoTxt;
    private javax.swing.JFormattedTextField FechaETxt;
    private javax.swing.JFormattedTextField FechaETxt1;
    private javax.swing.JLabel FechaNLbl;
    private javax.swing.JLabel FechaNLbl1;
    private javax.swing.JButton ListoLbl;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField NumeroEnvioTxt;
    private javax.swing.JTextField PrecioTxt;
    private javax.swing.JLabel SalarioLbl;
    private javax.swing.JLabel SalarioLbl3;
    private javax.swing.JLabel SalarioLbl4;
    private javax.swing.JLabel buscarLbl;
    private javax.swing.JComboBox<String> jComboBoxPaquete;
    private javax.swing.JComboBox<String> jComboBoxRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
